services:
  memos-ai:
    build: .
    container_name: memos-ai
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./memos_prod.db:/app/memos_prod.db
      - vector_db:/app/vector_db
    ports:
      - "9877:8000"

volumes:
  vector_db: