services:
  memos-ai:  # 添加服务名称
    image: registry.diyun.work/memos_ai:latest
    container_name: memos-ai
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./memos_prod.db:/app/memos_prod.db
      - ./vector_db:/app/vector_db
    ports:
      - "9877:8000"
